version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - mern-network
    depends_on:
      - mongo
    # volumes:
    #   - ./server:/usr/src/app   # Sync the server directory with the container

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - server
    # volumes:
    #   - ./client:/usr/src/app   # Sync the client directory with the container

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
